first attempt: copy [deep-link](https://github.com/tauri-apps/plugins-workspace/blob/v2/plugins/deep-link/src/lib.rs)
when called with a share text event, fails with :

type: crash
osVersion: google/sunfish/sunfish:13/TQ3A.230805.001.S1/2024092100:user/release-keys
package: net.coreact.app:1000
process: net.coreact.app
processUptime: 223 + 96 ms

java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{net.coreact.app/app.tauri.sharesheet.SharesheetPlugin}: java.lang.InstantiationException: java.lang.Class<app.tauri.sharesheet.SharesheetPlugin> has no zero argument constructor
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3561)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2313)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7940)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
Caused by: java.lang.InstantiationException: java.lang.Class<app.tauri.sharesheet.SharesheetPlugin> has no zero argument constructor
	at java.lang.Class.newInstance(Native Method)
	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
	at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
	at android.app.Instrumentation.newActivity(Instrumentation.java:1344)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3548)
	... 12 more